# Generated by Django 4.1.5 on 2023-01-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockAdvisor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Influencer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=99)),
            ],
        ),
    ]
